<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Test</RootNamespace>
    <AssemblyName>Project Z Test</AssemblyName>
    <UseWindowsForms>True</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <OptionStrict>On</OptionStrict>
    <StartupObject>Test.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="My Project\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibTessDotNet" Version="1.1.15" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project Z Audio\Project Z Audio.vbproj" />
    <ProjectReference Include="..\Project Z Windows.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Lidgren.Network">
      <HintPath>bin\Windows\Debug\Lidgren.Network.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="NAudio">
      <HintPath>..\Project Z Audio\bin\Debug\NAudio.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="NAudio.WindowsMediaFormat">
      <HintPath>..\Project Z Audio\bin\Debug\NAudio.WindowsMediaFormat.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Scenes\HostScene.vb" />
    <Compile Include="Scenes\MainScene.vb" />
    <Compile Include="zWindow.vb" />
    <Compile Include="Program.vb" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icon.ico" />
    <None Include="app.config" />
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_10.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_12.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_14.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_18.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_24.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_36.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_48.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_72.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="My Project\" />
  </ItemGroup>
</Project>
