<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>ProjectZ</RootNamespace>
    <AssemblyName>Project Z Audio</AssemblyName>
    <OptionStrict>Off</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionInfer>On</OptionInfer>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Project Z Extended Controls.sln.ide\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Project Z Extended Controls.v12.suo" />
    <None Remove="Project Z Extended Controls.v14.suo" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="nkast.Kni.Platform.WinForms.DX11" Version="4.2.9001" />
    <PackageReference Include="Speckle.Triangle" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="NAudio">
      <HintPath>bin\Debug\NAudio.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="NAudio.WindowsMediaFormat">
      <HintPath>bin\Debug\NAudio.WindowsMediaFormat.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Shared\Audio\ComplexTable.vb" />
    <Compile Include="Shared\Audio\IFFT.vb" />
    <Compile Include="Shared\Audio\LoopbackCapture.vb" />
    <Compile Include="Shared\Audio\MonitorSource.vb" />
    <Compile Include="Shared\Audio\PlaybackEngine.vb" />
    <Compile Include="Shared\Audio\Quantization\SignalMonitor.vb" />
    <Compile Include="Shared\Audio\SampleAggregator.vb" />
    <Compile Include="Shared\Audio\SampleToWaveProvider16.vb" />
    <Compile Include="Shared\Drawing\UI\Advanced\SegmentedSpectrumAnalyser.vb" />
    <Compile Include="Shared\Drawing\UI\Advanced\SpectrumAnalyser.vb" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project Z Windows.vbproj" />
  </ItemGroup>
</Project>
