#Region "Using Statements"
Imports System.Collections.Concurrent
Imports System.Collections.Generic
Imports System.Diagnostics
Imports System.Linq
Imports Designer.TowerDefense
Imports Microsoft.Xna.Framework
Imports Microsoft.Xna.Framework.Content
Imports Microsoft.Xna.Framework.Graphics
Imports Microsoft.Xna.Framework.Input
Imports Microsoft.Xna.Framework.Storage
Imports ProjectZ.Shared.Animations
Imports ProjectZ.Shared.Content
Imports ProjectZ.Shared.Drawing
Imports ProjectZ.Shared.Drawing.UI
Imports ProjectZ.Shared.Drawing.UI.Input
Imports ProjectZ.Shared.Drawing.UI.Primitives
Imports ProjectZ.Shared.Drawing.Designer
Imports SocketJack.Net
#End Region

''' <summary>
''' Main game scene for the Tower Defense game.
''' Handles UI, game logic, networking, and rendering.
''' UI elements are defined in MainScene.xaml and generated in MainScene.Designer.vb
''' </summary>
Partial Public Class MainScene
    Inherits Scene

#Region "Constants"

    Private Const PANEL_WIDTH As Single = 220.0F
    Private Const PATH_THICKNESS As Single = 28.0F
    Private Const BOMB_COST As Integer = 5
    Private Const ENEMY_KILL_REWARD As Integer = 8
    Private Const BOMB_KILL_REWARD As Integer = 5
    Private Const BOMB_DAMAGE As Single = 18.0F

    Private ReadOnly ToggleOnColor As New Color(60, 120, 60)
    Private ReadOnly ToggleOffColor As New Color(50, 50, 50)
    Private ReadOnly PathStartColor As New Color(20, 60, 20)
    Private ReadOnly PathEndColor As New Color(120, 200, 120)

#End Region

#Region "UI State Variables"

    Private SpiralTowerHome, PointTowerHome, BurstTowerHome As Vector2
    Private RapidTowerHome, SniperTowerHome, BombButtonHome As Vector2
    Private SelectedTower As Tower = Nothing
    Private TowerMenuVisible As Boolean = False
    Private TooltipVisible As Boolean = False
    Private LastMousePosition As Point
    Private DraggingTowerType As TowerType? = Nothing

#End Region

#Region "Game State - Collections"

    Private ReadOnly PathPoints As New List(Of Vector2)
    Private ReadOnly PathNodes As New List(Of CircleElement)
    Private ReadOnly PathSegments As New List(Of RectangleElement)

    Private ReadOnly Enemies As New List(Of Enemy)
    Private ReadOnly Bombs As New List(Of Bomb)
    Private ReadOnly HealthOrbs As New List(Of HealthOrb)
    Private ReadOnly Projectiles As New List(Of Projectile)
    Private ReadOnly Towers As New List(Of Tower)
    Private ReadOnly RippleEffects As New List(Of RippleEffect)

    Private ReadOnly EnemyLookup As New Dictionary(Of Guid, Enemy)
    Private ReadOnly BombLookup As New Dictionary(Of Guid, Bomb)
    Private ReadOnly HealthLookup As New Dictionary(Of Guid, HealthOrb)
    Private ReadOnly ProjectileLookup As New Dictionary(Of Guid, Projectile)
    Private ReadOnly TowerLookup As New Dictionary(Of Guid, Tower)

#End Region

#Region "Game State - Variables"

    Private Level As Integer = 1
    Private EnemiesRemaining As Integer = 0
    Private _currency As Integer = 100
    Private GameHealth As Integer = 20
    Private MaxGameHealth As Integer = 20
    Private EnemySpawnTimer As Single
    Private EnemiesToSpawn As Integer
    Private SelectedTowerType As TowerType = TowerType.Point
    Private ReadOnly Randomizer As New Random()
    Private LastWindowSize As Point
    Private GameRunning As Boolean
    Private NetworkInitialized As Boolean
    Private ManualNetworkMode As Boolean

    ''' <summary>
    ''' Currency property - returns max value in debug mode for testing.
    ''' In debug mode, the setter is ignored to prevent overflow.
    ''' </summary>
    Private Property Currency As Integer
        Get
#If DEBUG Then
            Return 999999
#Else
            Return _currency
#End If
        End Get
        Set(value As Integer)
#If Not DEBUG Then
            _currency = value
#End If
        End Set
    End Property

#End Region

#Region "Networking State"

    Private IsServer As Boolean = True
    Private Server As TcpServer
    Private Client As TcpClient
    Private ReadOnly PendingMap As New ConcurrentQueue(Of MapDataMessage)
    Private ReadOnly PendingStates As New ConcurrentQueue(Of GameStateMessage)
    Private NetworkTickTimer As Single
    Private ReadOnly NetworkTickRate As Single = 1.0F / 30.0F
    Private SentReady As Boolean
    Private MapReceived As Boolean

#End Region

#Region "Constructors and Initialization"

    Public Sub New()
    End Sub

    Public Sub New(ByRef SceneManager As SceneManager)
        MyBase.New(SceneManager)
        sender.Window.AllowUserResizing = True
        isCursorVisible = True

        ' Initialize UI from XAML (generated by Designer)
        InitializeComponent()

        ' Hide tower menu initially
        HideTowerMenu()

        ' Register event handlers
        AddHandler Me.OnMouseLeftClick, AddressOf HandleMouseLeftClick
        AddHandler Me.OnMouseRightClick, AddressOf HandleMouseRightClick
        AddHandler Me.OnKeyPress, AddressOf HandleKeyPress
        AddHandler Me.OnMouseMove, AddressOf HandleMouseMove
        AddHandler HostButton.MouseLeftClick, AddressOf HandleHostClicked
        AddHandler ClientButton.MouseLeftClick, AddressOf HandleClientClicked
        AddHandler StartButton.MouseLeftClick, AddressOf HandleStartClicked
        AddHandler StopButton.MouseLeftClick, AddressOf HandleStopClicked

        ' Tower menu event handlers
        AddHandler UpgradeButton.MouseLeftClick, AddressOf HandleUpgradeClicked
        AddHandler SellButton.MouseLeftClick, AddressOf HandleSellClicked
        AddHandler CloseMenuButton.MouseLeftClick, AddressOf HandleCloseMenuClicked
        AddHandler TargetFirstButton.MouseLeftClick, AddressOf HandleTargetFirstClicked
        AddHandler TargetLastButton.MouseLeftClick, AddressOf HandleTargetLastClicked
        AddHandler TargetClosestButton.MouseLeftClick, AddressOf HandleTargetClosestClicked
        AddHandler TargetStrongestButton.MouseLeftClick, AddressOf HandleTargetStrongestClicked
        AddHandler TargetWeakestButton.MouseLeftClick, AddressOf HandleTargetWeakestClicked
    End Sub

    Public Overrides Sub Initialize(gameTime As GameTime)
        MyBase.Initialize(gameTime)
        SetupLayout()
        UpdateNetworkUi()
        UpdateTowerButtonLabels()
    End Sub

#End Region

#Region "Main Game Loop"

    Public Overrides Sub Tick(gameTime As GameTime)
        MyBase.Tick(gameTime)
        Dim deltaSeconds As Single = CSng(gameTime.ElapsedGameTime.TotalSeconds)
        UpdateLayoutIfNeeded()
        UpdateRippleEffects(deltaSeconds)
        If GameRunning Then
            ProcessPendingNetwork()
            If IsServer Then
                UpdateServer(deltaSeconds)
            Else
                UpdateClient(deltaSeconds)
            End If
        End If
        UpdateHud()
        UpdateTooltip()
    End Sub

    Private Sub SetupLayout()
        Dim panelWidth As Single = 220.0F
        SidePanel.Position = Vector2.Zero
        SidePanel.Size = New Vector2(panelWidth, sender.Window.ClientBounds.Height)
        PlayField.Position = New Vector2(panelWidth, 0)
        PlayField.Size = New Vector2(sender.Window.ClientBounds.Width - panelWidth, sender.Window.ClientBounds.Height)
        EnemiesText.Position = New Vector2(16, 24)
        LevelText.Position = New Vector2(16, 56)
        CurrencyText.Position = New Vector2(16, 88)
        HealthText.Position = New Vector2(16, 120)
        TowerHintText.Position = New Vector2(16, 160)
        NetworkModeText.Position = New Vector2(16, 200)
        HostButton.Position = New Vector2(16, 230)
        ClientButton.Position = New Vector2(16, 270)
        StartButton.Position = New Vector2(16, 330)
        StopButton.Position = New Vector2(16, 370)
        SpiralTowerButton.Position = New Vector2(16, 430)
        PointTowerButton.Position = New Vector2(16, 470)
        BurstTowerButton.Position = New Vector2(16, 510)
        RapidTowerButton.Position = New Vector2(16, 550)
        SniperTowerButton.Position = New Vector2(16, 590)
        BombButton.Position = New Vector2(16, 640)
        SpiralTowerHome = SpiralTowerButton.Position
        PointTowerHome = PointTowerButton.Position
        BurstTowerHome = BurstTowerButton.Position
        RapidTowerHome = RapidTowerButton.Position
        SniperTowerHome = SniperTowerButton.Position
        BombButtonHome = BombButton.Position
        LastWindowSize = sender.Window.ClientBounds.Size
    End Sub

    Private Sub UpdateLayoutIfNeeded()
        Dim currentSize As Point = sender.Window.ClientBounds.Size
        If currentSize <> LastWindowSize Then
            Dim oldPlayFieldPosition As Vector2 = PlayField.Position
            Dim oldPlayFieldSize As Vector2 = PlayField.Size
            SetupLayout()
            If GameRunning AndAlso IsServer Then
                RescaleGameEntities(oldPlayFieldPosition, oldPlayFieldSize, PlayField.Position, PlayField.Size)
            End If
        End If
    End Sub

#End Region

#Region "Networking"

    Private Sub SetupNetwork()
        If Not ManualNetworkMode Then
            Dim args As String() = Environment.GetCommandLineArgs()
            If args.Any(Function(arg) arg.Equals("--client", StringComparison.OrdinalIgnoreCase)) Then
                IsServer = False
            ElseIf args.Any(Function(arg) arg.Equals("--server", StringComparison.OrdinalIgnoreCase)) Then
                IsServer = True
            End If
        End If

        If IsServer Then
            Server = New TcpServer(Port:=4040)
            Server.RegisterCallback(Of ClientReadyMessage)(AddressOf OnClientReady)
            Server.RegisterCallback(Of PlaceTowerMessage)(AddressOf OnPlaceTowerReceived)
            Server.Listen()
        End If

        Client = New TcpClient("TowerDefenseClient")
        Client.RegisterCallback(Of MapDataMessage)(AddressOf OnMapDataReceived)
        Client.RegisterCallback(Of GameStateMessage)(AddressOf OnGameStateReceived)
        Client.Connect("127.0.0.1", 4040)
        SentReady = False
    End Sub

    Private Sub RescalePath(oldPosition As Vector2, oldSize As Vector2, newPosition As Vector2, newSize As Vector2)
        If oldSize.X <= 0 OrElse oldSize.Y <= 0 Then Return
        If PathPoints.Count = 0 Then Return
        Dim scaleX As Single = newSize.X / oldSize.X
        Dim scaleY As Single = newSize.Y / oldSize.Y
        For i As Integer = 0 To PathPoints.Count - 1
            Dim relative As Vector2 = PathPoints(i) - oldPosition
            PathPoints(i) = newPosition + New Vector2(relative.X * scaleX, relative.Y * scaleY)
        Next
        For i As Integer = 0 To Math.Min(PathNodes.Count, PathPoints.Count) - 1
            PathNodes(i).Position = PathPoints(i) - New Vector2(5.0F)
        Next
        For Each segment As RectangleElement In PathSegments
            RemoveElement(segment)
        Next
        PathSegments.Clear()
        BuildPathSegments()
    End Sub

    ''' <summary>
    ''' Rescales all game entities (path, enemies, towers, bombs, health orbs, projectiles) when the window is resized.
    ''' </summary>
    Private Sub RescaleGameEntities(oldPosition As Vector2, oldSize As Vector2, newPosition As Vector2, newSize As Vector2)
        If oldSize.X <= 0 OrElse oldSize.Y <= 0 Then Return

        Dim scaleX As Single = newSize.X / oldSize.X
        Dim scaleY As Single = newSize.Y / oldSize.Y

        ' Rescale path
        RescalePath(oldPosition, oldSize, newPosition, newSize)

        ' Rescale enemies
        For Each enemy As Enemy In Enemies
            enemy.Position = RescalePosition(enemy.Position, oldPosition, oldSize, newPosition, newSize)
            enemy.UpdateVisual()
        Next

        ' Rescale towers
        For Each tower As Tower In Towers
            tower.Position = RescalePosition(tower.Position, oldPosition, oldSize, newPosition, newSize)
            tower.Range *= Math.Max(scaleX, scaleY) ' Scale range proportionally
            tower.UpdateVisual()
        Next

        ' Rescale bombs
        For Each bomb As Bomb In Bombs
            bomb.Position = RescalePosition(bomb.Position, oldPosition, oldSize, newPosition, newSize)
            bomb.UpdateVisual()
        Next

        ' Rescale health orbs
        For Each orb As HealthOrb In HealthOrbs
            orb.Position = RescalePosition(orb.Position, oldPosition, oldSize, newPosition, newSize)
            orb.UpdateVisual()
        Next

        ' Rescale projectiles
        For Each projectile As Projectile In Projectiles
            projectile.Position = RescalePosition(projectile.Position, oldPosition, oldSize, newPosition, newSize)
            projectile.UpdateVisual()
        Next

        ' Rescale ripple effects
        For Each ripple As RippleEffect In RippleEffects
            ripple.Position = RescalePosition(ripple.Position, oldPosition, oldSize, newPosition, newSize)
        Next
    End Sub

    ''' <summary>
    ''' Helper function to rescale a position from old playfield coordinates to new playfield coordinates.
    ''' </summary>
    Private Function RescalePosition(position As Vector2, oldPosition As Vector2, oldSize As Vector2, newPosition As Vector2, newSize As Vector2) As Vector2
        If oldSize.X <= 0 OrElse oldSize.Y <= 0 Then Return position
        Dim scaleX As Single = newSize.X / oldSize.X
        Dim scaleY As Single = newSize.Y / oldSize.Y
        Dim relative As Vector2 = position - oldPosition
        Return newPosition + New Vector2(relative.X * scaleX, relative.Y * scaleY)
    End Function

    Private Sub ProcessPendingNetwork()
        If IsServer Then
            ' Server doesn't process incoming game state
            Return
        End If

        ' Process all pending map data first (must be done before game state)
        Dim mapData As MapDataMessage = Nothing
        While PendingMap.TryDequeue(mapData)
            ApplyMap(mapData)
            MapReceived = True
        End While

        ' Only process game states after map has been received
        If MapReceived Then
            Dim state As GameStateMessage = Nothing
            While PendingStates.TryDequeue(state)
                ApplyGameState(state)
            End While
        End If

        ' Send ready message to server only after connection is established
        If Client IsNot Nothing AndAlso Client.Connected AndAlso Not SentReady Then
            SentReady = True
            Client.Send(New ClientReadyMessage())
        End If
    End Sub

    Private Sub OnClientReady(args As ReceivedEventArgs(Of ClientReadyMessage))
        If Not IsServer Then Return
        Dim mapMessage As New MapDataMessage With {
            .Path = New List(Of Vector2)(PathPoints),
            .PlayfieldSize = PlayField.Size,
            .SidePanelWidth = SidePanel.Size.X,
            .Level = Level
        }
        args.Connection.Send(mapMessage)
        ' Also send current game state immediately
        SendGameStateToConnection(args.Connection)
    End Sub

    Private Sub OnMapDataReceived(args As ReceivedEventArgs(Of MapDataMessage))
        PendingMap.Enqueue(args.Object)
    End Sub

    Private Sub OnGameStateReceived(args As ReceivedEventArgs(Of GameStateMessage))
        PendingStates.Enqueue(args.Object)
    End Sub

    Private Sub OnPlaceTowerReceived(args As ReceivedEventArgs(Of PlaceTowerMessage))
        If Not IsServer Then Return
        PlaceTowerInternal(args.Object.Position, args.Object.TowerType, True)
    End Sub

#End Region

#Region "Button Click Handlers"

    Private Sub HandleHostClicked(p As Point)
        If GameRunning Then Return
        ManualNetworkMode = True
        IsServer = True
        UpdateNetworkUi()
    End Sub

    Private Sub HandleClientClicked(p As Point)
        If GameRunning Then Return
        ManualNetworkMode = True
        IsServer = False
        UpdateNetworkUi()
    End Sub

    Private Sub HandleStartClicked(p As Point)
        If GameRunning Then Return
        If Not NetworkInitialized Then
            SetupNetwork()
            NetworkInitialized = True
        End If
        GameRunning = True
        GameHealth = MaxGameHealth
        If IsServer Then
            GenerateMap()
            StartLevel()
        End If
        UpdateNetworkUi()
    End Sub

    Private Sub HandleStopClicked(p As Point)
        If Not GameRunning Then Return
        StopGame()
    End Sub

#End Region

#Region "Game Logic"

    Private Sub StopGame(Optional resetHealth As Boolean = True)
        GameRunning = False
        EnemiesToSpawn = 0
        EnemiesRemaining = 0
        EnemySpawnTimer = 0.0F
        MapReceived = False
        SentReady = False
        If resetHealth Then
            GameHealth = MaxGameHealth
        End If
        For Each enemy As Enemy In Enemies.ToList()
            RemoveEnemy(enemy)
        Next
        For Each bomb As Bomb In Bombs.ToList()
            RemoveBomb(bomb)
        Next
        For Each orb As HealthOrb In HealthOrbs.ToList()
            RemoveHealthOrb(orb)
        Next
        For Each projectile As Projectile In Projectiles.ToList()
            RemoveProjectile(projectile)
        Next
        For Each tower As Tower In Towers.ToList()
            Towers.Remove(tower)
            TowerLookup.Remove(tower.Id)
            RemoveElement(tower.Visual)
        Next
        PathPoints.Clear()
        For Each node As CircleElement In PathNodes.ToList()
            RemoveElement(node)
        Next
        PathNodes.Clear()
        For Each segment As RectangleElement In PathSegments.ToList()
            RemoveElement(segment)
        Next
        PathSegments.Clear()
        For Each ripple As RippleEffect In RippleEffects.ToList()
            For Each visual In ripple.Visuals
                RemoveElement(visual)
            Next
        Next
        RippleEffects.Clear()
        UpdateNetworkUi()
    End Sub

    Private Sub UpdateServer(deltaSeconds As Single)
        If PathPoints.Count = 0 Then
            GenerateMap()
        End If

        EnemySpawnTimer -= deltaSeconds
        If EnemiesToSpawn > 0 AndAlso EnemySpawnTimer <= 0 Then
            SpawnEnemy()
            EnemiesToSpawn -= 1
            EnemySpawnTimer = 0.75F
        End If

        For Each enemy As Enemy In Enemies.ToList()
            enemy.Update(PathPoints, deltaSeconds)
            If enemy.ReachedEnd Then
                RemoveEnemy(enemy)
                GameHealth = Math.Max(0, GameHealth - 1)
                If GameHealth = 0 Then
                    StopGame(False)
                    Return
                End If
                Continue For
            End If
        Next

        For Each bomb As Bomb In Bombs.ToList()
            bomb.Update(deltaSeconds)
            If bomb.Countdown <= 0 Then
                ExplodeBomb(bomb)
            End If
        Next

        For Each projectile As Projectile In Projectiles.ToList()
            projectile.Update(deltaSeconds)
            If projectile.Lifetime > 4.0F Then
                RemoveProjectile(projectile)
            End If
        Next

        For Each tower As Tower In Towers
            tower.Update(deltaSeconds, Enemies, Projectiles, Me)
        Next

        ' Register any new projectiles created by towers
        For Each projectile As Projectile In Projectiles
            If Not ProjectileLookup.ContainsKey(projectile.Id) Then
                ProjectileLookup(projectile.Id) = projectile
                AddElement(projectile.Visual)
            End If
        Next

        HandleProjectileCollisions()
        HandleHealthPickups()

        If EnemiesRemaining = 0 AndAlso Enemies.Count = 0 AndAlso EnemiesToSpawn = 0 Then
            Level += 1
            StartLevel()
        End If

        NetworkTickTimer += deltaSeconds
        If NetworkTickTimer >= NetworkTickRate Then
            NetworkTickTimer = 0.0F
            SendGameState()
        End If
    End Sub

    Private Sub UpdateClient(deltaSeconds As Single)
        For Each bomb As Bomb In Bombs
            bomb.Update(deltaSeconds)
        Next
    End Sub

    Private Sub GenerateMap()
        SetupLayout()
        PathPoints.Clear()
        For Each node As CircleElement In PathNodes
            RemoveElement(node)
        Next
        PathNodes.Clear()
        For Each segment As RectangleElement In PathSegments
            RemoveElement(segment)
        Next
        PathSegments.Clear()

        Dim margin As Single = 60.0F
        Dim startX As Single = PlayField.Position.X + margin
        Dim endX As Single = PlayField.Position.X + PlayField.Size.X - margin
        Dim numCorners As Integer = 5
        Dim stepX As Single = (endX - startX) / numCorners
        Dim yRange As Single = PlayField.Size.Y - margin * 2.0F
        Dim currentPos As New Vector2(startX, PlayField.Position.Y + PlayField.Size.Y / 2.0F)
        PathPoints.Add(currentPos)
        For i As Integer = 1 To numCorners
            Dim targetX As Single = startX + stepX * i
            Dim targetY As Single = PlayField.Position.Y + margin + CSng(Randomizer.NextDouble()) * yRange
            ' Move horizontally first
            currentPos = New Vector2(targetX, currentPos.Y)
            PathPoints.Add(currentPos)
            ' Then move vertically
            currentPos = New Vector2(targetX, targetY)
            PathPoints.Add(currentPos)
        Next

        For Each point As Vector2 In PathPoints
            Dim marker As New CircleElement(Me) With {
                .Size = New Vector2(10.0F),
                .FillColor = Color.DimGray
            }
            marker.Position = point - New Vector2(5.0F)
            PathNodes.Add(marker)
            AddElement(marker)
        Next
        BuildPathSegments()
    End Sub

    Private Sub StartLevel()
        EnemiesToSpawn = 6 + (Level - 1) * 4
        EnemiesRemaining = EnemiesToSpawn
        EnemySpawnTimer = 0.5F
        SpawnHealthOrb()
    End Sub

    Private Sub SpawnEnemy()
        If PathPoints.Count = 0 Then Return
        Dim typeBlend As Single = CSng(Randomizer.NextDouble())
        Dim baseSpeed As Single = 70.0F + Level * 3.0F
        Dim baseHealth As Single = 22.0F + Level * 5.0F
        Dim speed As Single = Math.Max(35.0F, baseSpeed * (1.0F - typeBlend * 0.35F))
        Dim maxHealth As Single = baseHealth * (1.0F + typeBlend * 0.6F)
        Dim enemy As New Enemy(Me, PathPoints(0), 14.0F, speed, maxHealth, typeBlend)
        Enemies.Add(enemy)
        EnemyLookup(enemy.Id) = enemy
        AddElement(enemy.Visual)
    End Sub

    Private Sub PlaceBomb(position As Vector2)
        Dim countdown As Single = Math.Max(1.5F, 6.0F - Level * 0.3F)
        Dim bomb As New Bomb(Me, position, 16.0F, countdown, 80.0F)
        Bombs.Add(bomb)
        BombLookup(bomb.Id) = bomb
        AddElement(bomb.Visual)
        AddElement(bomb.TimerText)
    End Sub

    Private Sub SpawnHealthOrb()
        Dim position As Vector2 = GetRandomPointOnPath()
        Dim orb As New HealthOrb(Me, position, 12.0F, 5.0F)
        HealthOrbs.Add(orb)
        HealthLookup(orb.Id) = orb
        AddElement(orb.Visual)
    End Sub

    Private Function GetRandomPointOnPath() As Vector2
        If PathPoints.Count < 2 Then Return GetRandomPointInPlayfield()
        ' Pick a random segment
        Dim segmentIndex As Integer = Randomizer.Next(0, PathPoints.Count - 1)
        Dim startPoint As Vector2 = PathPoints(segmentIndex)
        Dim endPoint As Vector2 = PathPoints(segmentIndex + 1)
        ' Pick a random point along that segment
        Dim t As Single = CSng(Randomizer.NextDouble())
        Return Vector2.Lerp(startPoint, endPoint, t)
    End Function

    Private Function GetRandomPointInPlayfield() As Vector2
        Dim x As Single = PlayField.Position.X + 60.0F + CSng(Randomizer.NextDouble()) * (PlayField.Size.X - 120.0F)
        Dim y As Single = PlayField.Position.Y + 60.0F + CSng(Randomizer.NextDouble()) * (PlayField.Size.Y - 120.0F)
        Return New Vector2(x, y)
    End Function

    Private Sub ExplodeBomb(bomb As Bomb)
        Dim blast As New CircleCollider With {.Position = bomb.Position, .Radius = bomb.ExplosionRadius}
        For Each enemy As Enemy In Enemies.ToList()
            If blast.Intersects(enemy.Collider()) Then
                enemy.Health -= BOMB_DAMAGE
                If enemy.IsDead() Then
                    RemoveEnemy(enemy)
                    Currency += BOMB_KILL_REWARD
                End If
            End If
        Next
        RemoveBomb(bomb)
    End Sub

    Private Sub HandleProjectileCollisions()
        For Each projectile As Projectile In Projectiles.ToList()
            Dim hit As Boolean = False
            For Each enemy As Enemy In Enemies.ToList()
                If projectile.Collider().Intersects(enemy.Collider()) Then
                    enemy.Health -= projectile.Damage
                    hit = True
                    If enemy.IsDead() Then
                        RemoveEnemy(enemy)
                        Currency += ENEMY_KILL_REWARD
                    End If
                    Exit For
                End If
            Next
            If hit Then
                RemoveProjectile(projectile)
            End If
        Next
    End Sub

    Private Sub HandleHealthPickups()
        For Each orb As HealthOrb In HealthOrbs.ToList()
            For Each enemy As Enemy In Enemies.ToList()
                If orb.Collider().Intersects(enemy.Collider()) Then
                    enemy.Health = Math.Min(enemy.MaxHealth, enemy.Health + orb.Amount)
                    RemoveHealthOrb(orb)
                    Exit For
                End If
            Next
        Next
    End Sub

    Private Sub RemoveEnemy(enemy As Enemy)
        If enemy Is Nothing Then Return
        Enemies.Remove(enemy)
        EnemyLookup.Remove(enemy.Id)
        RemoveElement(enemy.Visual)
        EnemiesRemaining = Math.Max(0, EnemiesRemaining - 1)
    End Sub

    Private Sub RemoveBomb(bomb As Bomb)
        Bombs.Remove(bomb)
        BombLookup.Remove(bomb.Id)
        RemoveElement(bomb.Visual)
        RemoveElement(bomb.TimerText)
    End Sub

    Private Sub RemoveHealthOrb(orb As HealthOrb)
        HealthOrbs.Remove(orb)
        HealthLookup.Remove(orb.Id)
        RemoveElement(orb.Visual)
    End Sub

    Private Sub RemoveProjectile(projectile As Projectile)
        Projectiles.Remove(projectile)
        ProjectileLookup.Remove(projectile.Id)
        RemoveElement(projectile.Visual)
    End Sub

    Private Sub SendGameState()
        If Server Is Nothing Then Return
        Dim state As New GameStateMessage With {
            .Enemies = Enemies.Select(Function(enemy) New EnemyState With {
                .Id = enemy.Id,
                .Position = enemy.Position,
                .Radius = enemy.Radius,
                .Health = enemy.Health,
                .MaxHealth = enemy.MaxHealth,
                .TypeBlend = enemy.TypeBlend
            }).ToList(),
            .Bombs = Bombs.Select(Function(bomb) New BombState With {
                .Id = bomb.Id,
                .Position = bomb.Position,
                .Radius = bomb.Radius,
                .Countdown = bomb.Countdown,
                .ExplosionRadius = bomb.ExplosionRadius
            }).ToList(),
            .HealthOrbs = HealthOrbs.Select(Function(orb) New HealthState With {
                .Id = orb.Id,
                .Position = orb.Position,
                .Radius = orb.Radius,
                .Amount = orb.Amount
            }).ToList(),
            .Projectiles = Projectiles.Select(Function(proj) New ProjectileState With {
                .Id = proj.Id,
                .Position = proj.Position,
                .Radius = proj.Radius,
                .Velocity = proj.RigidBody.Velocity
            }).ToList(),
            .Towers = Towers.Select(Function(tower) New TowerState With {
                .Id = tower.Id,
                .Position = tower.Position,
                .TowerType = GetTowerType(tower)
            }).ToList(),
            .Level = Level,
            .Currency = Currency,
            .EnemiesRemaining = EnemiesRemaining,
            .GameHealth = GameHealth,
            .MaxGameHealth = MaxGameHealth
        }
        Server.SendBroadcast(state)
    End Sub

    Private Sub SendGameStateToConnection(connection As SocketJack.Net.NetworkConnection)
        If connection Is Nothing Then Return
        Dim state As New GameStateMessage With {
            .Enemies = Enemies.Select(Function(enemy) New EnemyState With {
                .Id = enemy.Id,
                .Position = enemy.Position,
                .Radius = enemy.Radius,
                .Health = enemy.Health,
                .MaxHealth = enemy.MaxHealth,
                .TypeBlend = enemy.TypeBlend
            }).ToList(),
            .Bombs = Bombs.Select(Function(bomb) New BombState With {
                .Id = bomb.Id,
                .Position = bomb.Position,
                .Radius = bomb.Radius,
                .Countdown = bomb.Countdown,
                .ExplosionRadius = bomb.ExplosionRadius
            }).ToList(),
            .HealthOrbs = HealthOrbs.Select(Function(orb) New HealthState With {
                .Id = orb.Id,
                .Position = orb.Position,
                .Radius = orb.Radius,
                .Amount = orb.Amount
            }).ToList(),
            .Projectiles = Projectiles.Select(Function(proj) New ProjectileState With {
                .Id = proj.Id,
                .Position = proj.Position,
                .Radius = proj.Radius,
                .Velocity = proj.RigidBody.Velocity
            }).ToList(),
            .Towers = Towers.Select(Function(tower) New TowerState With {
                .Id = tower.Id,
                .Position = tower.Position,
                .TowerType = GetTowerType(tower)
            }).ToList(),
            .Level = Level,
            .Currency = Currency,
            .EnemiesRemaining = EnemiesRemaining,
            .GameHealth = GameHealth,
            .MaxGameHealth = MaxGameHealth
        }
        connection.Send(state)
    End Sub

    Private Function GetTowerType(tower As Tower) As TowerType
        If TypeOf tower Is SpiralTower Then Return TowerType.Spiral
        If TypeOf tower Is BurstTower Then Return TowerType.Burst
        If TypeOf tower Is RapidTower Then Return TowerType.Rapid
        If TypeOf tower Is SniperTower Then Return TowerType.Sniper
        Return TowerType.Point
    End Function

    Private Sub ApplyMap(mapData As MapDataMessage)
        Level = mapData.Level
        SidePanel.Size = New Vector2(mapData.SidePanelWidth, sender.Window.ClientBounds.Height)
        PlayField.Position = New Vector2(mapData.SidePanelWidth, 0)
        PlayField.Size = mapData.PlayfieldSize
        PathPoints.Clear()
        PathPoints.AddRange(mapData.Path)
        For Each node As CircleElement In PathNodes
            RemoveElement(node)
        Next
        PathNodes.Clear()
        For Each segment As RectangleElement In PathSegments
            RemoveElement(segment)
        Next
        PathSegments.Clear()
        For Each point As Vector2 In PathPoints
            Dim marker As New CircleElement(Me) With {
                .Size = New Vector2(10.0F),
                .FillColor = Color.DimGray
            }
            marker.Position = point - New Vector2(5.0F)
            PathNodes.Add(marker)
            AddElement(marker)
        Next
        BuildPathSegments()
    End Sub

    Private Sub ApplyGameState(state As GameStateMessage)
        Level = state.Level
        Currency = state.Currency
        EnemiesRemaining = state.EnemiesRemaining
        GameHealth = state.GameHealth
        MaxGameHealth = state.MaxGameHealth

        SyncEnemies(state.Enemies)
        SyncBombs(state.Bombs)
        SyncHealthOrbs(state.HealthOrbs)
        SyncProjectiles(state.Projectiles)
        SyncTowers(state.Towers)
        If GameRunning AndAlso GameHealth <= 0 Then
            StopGame(False)
        End If
    End Sub

    Private Sub SyncEnemies(states As List(Of EnemyState))
        Dim activeIds As New HashSet(Of Guid)(states.Select(Function(s) s.Id))
        For Each enemy As Enemy In Enemies.ToList()
            If Not activeIds.Contains(enemy.Id) Then
                RemoveEnemy(enemy)
            End If
        Next

        For Each state As EnemyState In states
            Dim enemy As Enemy = Nothing
            If Not EnemyLookup.TryGetValue(state.Id, enemy) Then
                enemy = New Enemy(Me, state.Position, state.Radius, 0.0F, state.MaxHealth, state.TypeBlend)
                enemy.Id = state.Id
                Enemies.Add(enemy)
                EnemyLookup(enemy.Id) = enemy
                AddElement(enemy.Visual)
            End If
            enemy.Position = state.Position
            enemy.Health = state.Health
            enemy.MaxHealth = state.MaxHealth
            enemy.TypeBlend = state.TypeBlend
            enemy.UpdateVisual()
        Next
    End Sub

    Private Sub SyncBombs(states As List(Of BombState))
        Dim activeIds As New HashSet(Of Guid)(states.Select(Function(s) s.Id))
        For Each bomb As Bomb In Bombs.ToList()
            If Not activeIds.Contains(bomb.Id) Then
                RemoveBomb(bomb)
            End If
        Next

        For Each state As BombState In states
            Dim bomb As Bomb = Nothing
            If Not BombLookup.TryGetValue(state.Id, bomb) Then
                bomb = New Bomb(Me, state.Position, state.Radius, state.Countdown, state.ExplosionRadius)
                bomb.Id = state.Id
                Bombs.Add(bomb)
                BombLookup(bomb.Id) = bomb
                AddElement(bomb.Visual)
                AddElement(bomb.TimerText)
            End If
            bomb.Position = state.Position
            bomb.Countdown = state.Countdown
            bomb.ExplosionRadius = state.ExplosionRadius
            bomb.UpdateVisual()
        Next
    End Sub

    Private Sub SyncHealthOrbs(states As List(Of HealthState))
        Dim activeIds As New HashSet(Of Guid)(states.Select(Function(s) s.Id))
        For Each orb As HealthOrb In HealthOrbs.ToList()
            If Not activeIds.Contains(orb.Id) Then
                RemoveHealthOrb(orb)
            End If
        Next

        For Each state As HealthState In states
            Dim orb As HealthOrb = Nothing
            If Not HealthLookup.TryGetValue(state.Id, orb) Then
                orb = New HealthOrb(Me, state.Position, state.Radius, state.Amount)
                orb.Id = state.Id
                HealthOrbs.Add(orb)
                HealthLookup(orb.Id) = orb
                AddElement(orb.Visual)
            End If
            orb.Position = state.Position
            orb.Amount = state.Amount
            orb.UpdateVisual()
        Next
    End Sub

    Private Sub SyncProjectiles(states As List(Of ProjectileState))
        Dim activeIds As New HashSet(Of Guid)(states.Select(Function(s) s.Id))
        For Each projectile As Projectile In Projectiles.ToList()
            If Not activeIds.Contains(projectile.Id) Then
                RemoveProjectile(projectile)
            End If
        Next

        For Each state As ProjectileState In states
            Dim projectile As Projectile = Nothing
            If Not ProjectileLookup.TryGetValue(state.Id, projectile) Then
                projectile = New Projectile(Me, state.Position, state.Radius, state.Velocity, 0.0F, 1.0F)
                projectile.Id = state.Id
                Projectiles.Add(projectile)
                ProjectileLookup(projectile.Id) = projectile
                AddElement(projectile.Visual)
            End If
            projectile.Position = state.Position
            projectile.RigidBody.Velocity = state.Velocity
            projectile.UpdateVisual()
        Next
    End Sub

    Private Sub SyncTowers(states As List(Of TowerState))
        Dim activeIds As New HashSet(Of Guid)(states.Select(Function(s) s.Id))
        For Each tower As Tower In Towers.ToList()
            If Not activeIds.Contains(tower.Id) Then
                Towers.Remove(tower)
                TowerLookup.Remove(tower.Id)
                RemoveElement(tower.Visual)
            End If
        Next

        For Each state As TowerState In states
            Dim tower As Tower = Nothing
            If Not TowerLookup.TryGetValue(state.Id, tower) Then
                tower = CreateTower(state.TowerType, state.Position)
                tower.Id = state.Id
                Towers.Add(tower)
                TowerLookup(tower.Id) = tower
                AddElement(tower.Visual)
                SpawnTowerPlacementEffect(state.Position) ' Ripple effect for network-synced towers
            End If
            tower.Position = state.Position
            tower.UpdateVisual()
        Next
    End Sub

#End Region

#Region "Input Handling"

    Private Sub HandleMouseLeftClick(p As Point)
        Dim clickPosition As New Vector2(p.X, p.Y)

        ' If menu is visible and click is outside menu, close it
        If TowerMenuVisible Then
            If Not IsOverTowerMenu(clickPosition) Then
                HideTowerMenu()
            End If
            Return
        End If

        If Not GameRunning Then Return
        If Not IsInPlayField(clickPosition) Then Return

        ' Check if clicked on a tower
        Dim tower As Tower = FindTowerAt(clickPosition)
        If tower IsNot Nothing AndAlso IsServer Then
            ShowTowerMenu(tower)
        End If
    End Sub

    Private Sub HandleMouseRightClick(p As Point)
        Dim clickPosition As New Vector2(p.X, p.Y)
        If TowerMenuVisible Then
            HideTowerMenu()
            Return
        End If
    End Sub

    Private Sub HandleKeyPress(key As Keys, keyboardState As KeyboardState)
        If key = Keys.Escape AndAlso TowerMenuVisible Then
            HideTowerMenu()
        End If
    End Sub

    Private Sub PlaceTowerInternal(position As Vector2, towerType As TowerType, ignoreCurrency As Boolean)
        Dim tower As Tower = CreateTower(towerType, position)
        If tower Is Nothing Then Return
        If Not IsInPlayField(position) Then Return
        If IsOnPath(position) Then Return
        If Not ignoreCurrency AndAlso Currency < tower.Cost Then Return
        If Not ignoreCurrency Then
            Currency -= tower.Cost
        End If
        Towers.Add(tower)
        TowerLookup(tower.Id) = tower
        AddElement(tower.Visual)
        SpawnTowerPlacementEffect(position)
    End Sub

    Private Function CreateTower(towerType As TowerType, position As Vector2) As Tower
        Select Case towerType
            Case TowerType.Spiral
                Return New SpiralTower(Me, position)
            Case TowerType.Burst
                Return New BurstTower(Me, position)
            Case TowerType.Rapid
                Return New RapidTower(Me, position)
            Case TowerType.Sniper
                Return New SniperTower(Me, position)
            Case Else
                Return New PointTower(Me, position)
        End Select
    End Function

    Private Sub SpawnTowerPlacementEffect(position As Vector2)
        Dim ripple As New RippleEffect(Me, position, 50.0F, 0.4F)
        For Each visual In ripple.Visuals
            AddElement(visual)
        Next
        RippleEffects.Add(ripple)
    End Sub

    Private Sub UpdateRippleEffects(deltaSeconds As Single)
        For i As Integer = RippleEffects.Count - 1 To 0 Step -1
            Dim ripple = RippleEffects(i)
            If ripple.Update(deltaSeconds) Then
                ' Effect complete, remove visuals
                For Each visual In ripple.Visuals
                    RemoveElement(visual)
                Next
                RippleEffects.RemoveAt(i)
            End If
        Next
    End Sub

#End Region

#Region "UI Updates"

    Private Sub UpdateHud()
        EnemiesText.Text = $"Enemies: {EnemiesRemaining}"
        LevelText.Text = $"Level: {Level}"
        CurrencyText.Text = $"Currency: {Currency}"
        HealthText.Text = $"Health: {GameHealth}/{MaxGameHealth}"
    End Sub

    Private Sub UpdateNetworkUi()
        NetworkModeText.Text = If(IsServer, "Mode: Host", "Mode: Client")
        HostButton.isEnabled = Not GameRunning
        ClientButton.isEnabled = Not GameRunning
        StartButton.isEnabled = Not GameRunning
        StopButton.isEnabled = GameRunning
        SpiralTowerButton.isEnabled = GameRunning
        PointTowerButton.isEnabled = GameRunning
        BurstTowerButton.isEnabled = GameRunning
        RapidTowerButton.isEnabled = GameRunning
        SniperTowerButton.isEnabled = GameRunning
        BombButton.isEnabled = GameRunning
        SetButtonToggle(HostButton, IsServer)
        SetButtonToggle(ClientButton, Not IsServer)
        SetButtonToggle(StartButton, GameRunning)
        SetButtonToggle(StopButton, GameRunning)
    End Sub

    Private Sub SetButtonToggle(button As Button, isOn As Boolean)
        button.BackgroundColor = If(isOn, ToggleOnColor, ToggleOffColor)
    End Sub

    Private Sub UpdateTowerButtonLabels()
        SpiralTowerButton.Text = $"Spiral (${GetTowerCost(TowerType.Spiral)})"
        PointTowerButton.Text = $"Point (${GetTowerCost(TowerType.Point)})"
        BurstTowerButton.Text = $"Burst (${GetTowerCost(TowerType.Burst)})"
        RapidTowerButton.Text = $"Rapid (${GetTowerCost(TowerType.Rapid)})"
        SniperTowerButton.Text = $"Sniper (${GetTowerCost(TowerType.Sniper)})"
    End Sub

    Private Function GetTowerCost(towerType As TowerType) As Integer
        Select Case towerType
            Case TowerType.Spiral
                Return 65
            Case TowerType.Burst
                Return 75
            Case TowerType.Rapid
                Return 40
            Case TowerType.Sniper
                Return 90
            Case Else
                Return 50
        End Select
    End Function

    Private Sub BuildPathSegments()
        Dim thickness As Single = 28.0F
        Dim startColor As New Color(20, 60, 20)
        Dim endColor As New Color(120, 200, 120)
        For i As Integer = 0 To PathPoints.Count - 2
            Dim start As Vector2 = PathPoints(i)
            Dim [end] As Vector2 = PathPoints(i + 1)
            Dim blend As Single = If(PathPoints.Count <= 2, 1.0F, CSng(i) / CSng(PathPoints.Count - 2))
            Dim minX As Single = Math.Min(start.X, [end].X) - thickness / 2.0F
            Dim minY As Single = Math.Min(start.Y, [end].Y) - thickness / 2.0F
            Dim width As Single = Math.Abs(start.X - [end].X) + thickness
            Dim height As Single = Math.Abs(start.Y - [end].Y) + thickness
            Dim segment As New RectangleElement(Me) With {
                .BackgroundColor = Color.Lerp(startColor, endColor, blend),
                .isMovable = False,
                .isMouseBypassEnabled = True
            }
            segment.Position = New Vector2(minX, minY)
            segment.Size = New Vector2(width, height)
            PathSegments.Add(segment)
            AddElement(segment)
        Next
    End Sub

    Private Function IsOnPath(position As Vector2) As Boolean
        For Each segment As RectangleElement In PathSegments
            Dim rect As New Rectangle(CInt(segment.Position.X), CInt(segment.Position.Y), CInt(segment.Size.X), CInt(segment.Size.Y))
            If rect.Contains(CInt(position.X), CInt(position.Y)) Then
                Return True
            End If
        Next
        Return False
    End Function

    Private Function IsInPlayField(position As Vector2) As Boolean
        Dim rect As New Rectangle(CInt(PlayField.Position.X), CInt(PlayField.Position.Y), CInt(PlayField.Size.X), CInt(PlayField.Size.Y))
        Return rect.Contains(CInt(position.X), CInt(position.Y))
    End Function

#End Region

#Region "Drag and Drop Handlers"

    Private Sub SpiralTowerButton_DragDrop(p As Point, element As SceneElement) Handles SpiralTowerButton.DragDrop
        HandleTowerDrop(TowerType.Spiral, p)
        ResetTowerButtons()
        HideRangeIndicator()
        DraggingTowerType = Nothing
    End Sub

    Private Sub PointTowerButton_DragDrop(p As Point, element As SceneElement) Handles PointTowerButton.DragDrop
        HandleTowerDrop(TowerType.Point, p)
        ResetTowerButtons()
        HideRangeIndicator()
        DraggingTowerType = Nothing
    End Sub

    Private Sub BurstTowerButton_DragDrop(p As Point, element As SceneElement) Handles BurstTowerButton.DragDrop
        HandleTowerDrop(TowerType.Burst, p)
        ResetTowerButtons()
        HideRangeIndicator()
        DraggingTowerType = Nothing
    End Sub

    Private Sub RapidTowerButton_DragDrop(p As Point, element As SceneElement) Handles RapidTowerButton.DragDrop
        HandleTowerDrop(TowerType.Rapid, p)
        ResetTowerButtons()
        HideRangeIndicator()
        DraggingTowerType = Nothing
    End Sub

    Private Sub SniperTowerButton_DragDrop(p As Point, element As SceneElement) Handles SniperTowerButton.DragDrop
        HandleTowerDrop(TowerType.Sniper, p)
        ResetTowerButtons()
        HideRangeIndicator()
        DraggingTowerType = Nothing
    End Sub

    Private Sub BombButton_DragDrop(p As Point, element As SceneElement) Handles BombButton.DragDrop
        HandleBombDrop(p)
        ResetTowerButtons()
        HideRangeIndicator()
        DraggingTowerType = Nothing
    End Sub

    ' Drag event handlers to show range preview while dragging
    Private Sub SpiralTowerButton_MouseDrag(currentPoint As Point, startPoint As Point) Handles SpiralTowerButton.MouseDrag
        HandleTowerDrag(TowerType.Spiral, currentPoint)
    End Sub

    Private Sub PointTowerButton_MouseDrag(currentPoint As Point, startPoint As Point) Handles PointTowerButton.MouseDrag
        HandleTowerDrag(TowerType.Point, currentPoint)
    End Sub

    Private Sub BurstTowerButton_MouseDrag(currentPoint As Point, startPoint As Point) Handles BurstTowerButton.MouseDrag
        HandleTowerDrag(TowerType.Burst, currentPoint)
    End Sub

    Private Sub RapidTowerButton_MouseDrag(currentPoint As Point, startPoint As Point) Handles RapidTowerButton.MouseDrag
        HandleTowerDrag(TowerType.Rapid, currentPoint)
    End Sub

    Private Sub SniperTowerButton_MouseDrag(currentPoint As Point, startPoint As Point) Handles SniperTowerButton.MouseDrag
        HandleTowerDrag(TowerType.Sniper, currentPoint)
    End Sub

    Private Sub HandleTowerDrag(towerType As TowerType, currentPoint As Point)
        If Not GameRunning Then
            HideRangeIndicator()
            Return
        End If
        Dim dragPosition As New Vector2(currentPoint.X, currentPoint.Y)
        If IsInPlayField(dragPosition) Then
            Dim range As Single = GetTowerRange(towerType)
            Dim isValidPlacement As Boolean = Not IsOnPath(dragPosition)
            ' Show green if valid, red if invalid
            RangeIndicator.FillColor = If(isValidPlacement, New Color(100, 200, 100, 60), New Color(200, 100, 100, 60))
            ShowRangeIndicator(dragPosition, range)
            DraggingTowerType = towerType
        Else
            HideRangeIndicator()
        End If
    End Sub

    Private Sub HandleTowerDrop(towerType As TowerType, p As Point)
        If Not GameRunning Then Return
        Dim dropPosition As New Vector2(p.X, p.Y)
        If Not IsInPlayField(dropPosition) Then Return
        If IsOnPath(dropPosition) Then Return
        If IsServer Then
            PlaceTowerInternal(dropPosition, towerType, False)
        ElseIf Client IsNot Nothing Then
            Client.Send(New PlaceTowerMessage With {.Position = dropPosition, .TowerType = towerType})
        End If
    End Sub

    Private Sub HandleBombDrop(p As Point)
        If Not GameRunning Then Return
        If Not IsServer Then Return
        Dim dropPosition As New Vector2(p.X, p.Y)
        If Not IsInPlayField(dropPosition) Then Return
        If Not IsOnPath(dropPosition) Then Return
        If Currency < BOMB_COST Then Return
        Currency -= BOMB_COST
        PlaceBomb(dropPosition)
    End Sub

    Private Sub ResetTowerButtons()
        SpiralTowerButton.Position = SpiralTowerHome
        PointTowerButton.Position = PointTowerHome
        BurstTowerButton.Position = BurstTowerHome
        RapidTowerButton.Position = RapidTowerHome
        SniperTowerButton.Position = SniperTowerHome
        BombButton.Position = BombButtonHome
    End Sub

    Private Function FindTowerAt(position As Vector2) As Tower
        For Each tower As Tower In Towers
            Dim radius As Single = tower.Visual.Size.X / 2.0F
            Dim distance As Single = Vector2.DistanceSquared(tower.Position, position)
            If distance <= radius * radius Then
                Return tower
            End If
        Next
        Return Nothing
    End Function

#End Region

#Region "Tower Menu"

    Private Sub BringTowerMenuToFront()
        ' Remove and re-add menu elements to bring them to front
        RemoveElement(TowerMenuBackground)
        RemoveElement(TowerMenuTitle)
        RemoveElement(UpgradeButton)
        RemoveElement(SellButton)
        RemoveElement(TargetFirstButton)
        RemoveElement(TargetLastButton)
        RemoveElement(TargetClosestButton)
        RemoveElement(TargetStrongestButton)
        RemoveElement(TargetWeakestButton)
        RemoveElement(CloseMenuButton)

        AddElement(TowerMenuBackground)
        AddElement(TowerMenuTitle)
        AddElement(UpgradeButton)
        AddElement(SellButton)
        AddElement(TargetFirstButton)
        AddElement(TargetLastButton)
        AddElement(TargetClosestButton)
        AddElement(TargetStrongestButton)
        AddElement(TargetWeakestButton)
        AddElement(CloseMenuButton)
    End Sub

    Private Sub ShowTowerMenu(tower As Tower)
        SelectedTower = tower
        TowerMenuVisible = True

        ' Bring menu elements to front
        BringTowerMenuToFront()

        ' Position menu near the tower
        Dim menuWidth As Single = 160.0F
        Dim menuHeight As Single = 200.0F
        Dim menuX As Single = tower.Position.X + 30.0F
        Dim menuY As Single = tower.Position.Y - menuHeight / 2.0F

        ' Keep menu on screen
        If menuX + menuWidth > sender.Window.ClientBounds.Width Then
            menuX = tower.Position.X - menuWidth - 30.0F
        End If
        If menuY < 0 Then menuY = 10.0F
        If menuY + menuHeight > sender.Window.ClientBounds.Height Then
            menuY = sender.Window.ClientBounds.Height - menuHeight - 10.0F
        End If

        TowerMenuBackground.Position = New Vector2(menuX, menuY)
        TowerMenuBackground.Size = New Vector2(menuWidth, menuHeight)

        ' Position menu elements
        Dim padding As Single = 10.0F
        Dim yOffset As Single = menuY + padding

        CloseMenuButton.Position = New Vector2(menuX + menuWidth - 30.0F, yOffset)
        TowerMenuTitle.Position = New Vector2(menuX + padding, yOffset + 2.0F)
        yOffset += 30.0F

        ' Upgrade button
        UpgradeButton.Position = New Vector2(menuX + padding, yOffset)
        If tower.CanUpgrade() Then
            UpgradeButton.Text = $"Upgrade (${tower.UpgradeCost})"
            UpgradeButton.isEnabled = Currency >= tower.UpgradeCost
        Else
            UpgradeButton.Text = "Max Level"
            UpgradeButton.isEnabled = False
        End If
        yOffset += 34.0F

        ' Sell button
        SellButton.Position = New Vector2(menuX + padding, yOffset)
        SellButton.Text = $"Sell (${tower.GetSellValue()})"
        yOffset += 40.0F

        ' Targeting label and buttons
        Dim targetY As Single = yOffset
        Dim btnWidth As Single = 65.0F
        Dim btnSpacing As Single = 2.0F

        TargetFirstButton.Position = New Vector2(menuX + padding, targetY)
        TargetLastButton.Position = New Vector2(menuX + padding + btnWidth + btnSpacing, targetY)
        targetY += 28.0F

        TargetClosestButton.Position = New Vector2(menuX + padding, targetY)
        TargetStrongestButton.Position = New Vector2(menuX + padding + btnWidth + btnSpacing, targetY)
        targetY += 28.0F

        TargetWeakestButton.Position = New Vector2(menuX + padding, targetY)

        UpdateTargetingButtonColors()
        TowerMenuTitle.Text = $"{tower.GetType().Name.Replace("Tower", "")} Lv.{tower.Level}"

        ' Show range indicator around the selected tower
        ShowRangeIndicator(tower.Position, tower.Range)
    End Sub

    Private Sub HideTowerMenu()
        TowerMenuVisible = False
        SelectedTower = Nothing

        ' Hide range indicator
        HideRangeIndicator()

        ' Move menu elements off-screen
        Dim offScreen As New Vector2(-1000, -1000)
        TowerMenuBackground.Position = offScreen
        TowerMenuTitle.Position = offScreen
        UpgradeButton.Position = offScreen
        SellButton.Position = offScreen
        TargetFirstButton.Position = offScreen
        TargetLastButton.Position = offScreen
        TargetClosestButton.Position = offScreen
        TargetStrongestButton.Position = offScreen
        TargetWeakestButton.Position = offScreen
        CloseMenuButton.Position = offScreen
    End Sub

    Private Function IsOverTowerMenu(position As Vector2) As Boolean
        If Not TowerMenuVisible Then Return False
        Dim rect As New Rectangle(
            CInt(TowerMenuBackground.Position.X),
            CInt(TowerMenuBackground.Position.Y),
            CInt(TowerMenuBackground.Size.X),
            CInt(TowerMenuBackground.Size.Y))
        Return rect.Contains(CInt(position.X), CInt(position.Y))
    End Function

    Private Sub UpdateTargetingButtonColors()
        If SelectedTower Is Nothing Then Return

        Dim defaultColor As New Color(60, 60, 60)
        Dim selectedColor As New Color(80, 140, 80)

        TargetFirstButton.BackgroundColor = If(SelectedTower.Targeting = TargetingMode.First, selectedColor, defaultColor)
        TargetLastButton.BackgroundColor = If(SelectedTower.Targeting = TargetingMode.Last, selectedColor, defaultColor)
        TargetClosestButton.BackgroundColor = If(SelectedTower.Targeting = TargetingMode.Closest, selectedColor, defaultColor)
        TargetStrongestButton.BackgroundColor = If(SelectedTower.Targeting = TargetingMode.Strongest, selectedColor, defaultColor)
        TargetWeakestButton.BackgroundColor = If(SelectedTower.Targeting = TargetingMode.Weakest, selectedColor, defaultColor)
    End Sub

    Private Sub HandleUpgradeClicked(p As Point)
        If SelectedTower Is Nothing OrElse Not SelectedTower.CanUpgrade() Then Return
        If Currency < SelectedTower.UpgradeCost Then Return
        Dim cost As Integer = 0
        If SelectedTower.Upgrade(cost) Then
            Currency -= cost
            ShowTowerMenu(SelectedTower) ' Refresh menu
        End If
    End Sub

    Private Sub HandleSellClicked(p As Point)
        If SelectedTower Is Nothing Then Return
        Dim sellValue As Integer = SelectedTower.GetSellValue()
        Currency += sellValue
        RemoveTower(SelectedTower)
        HideTowerMenu()
    End Sub

    Private Sub HandleCloseMenuClicked(p As Point)
        HideTowerMenu()
    End Sub

    Private Sub HandleTargetFirstClicked(p As Point)
        If SelectedTower IsNot Nothing Then
            SelectedTower.Targeting = TargetingMode.First
            UpdateTargetingButtonColors()
        End If
    End Sub

    Private Sub HandleTargetLastClicked(p As Point)
        If SelectedTower IsNot Nothing Then
            SelectedTower.Targeting = TargetingMode.Last
            UpdateTargetingButtonColors()
        End If
    End Sub

    Private Sub HandleTargetClosestClicked(p As Point)
        If SelectedTower IsNot Nothing Then
            SelectedTower.Targeting = TargetingMode.Closest
            UpdateTargetingButtonColors()
        End If
    End Sub

    Private Sub HandleTargetStrongestClicked(p As Point)
        If SelectedTower IsNot Nothing Then
            SelectedTower.Targeting = TargetingMode.Strongest
            UpdateTargetingButtonColors()
        End If
    End Sub

    Private Sub HandleTargetWeakestClicked(p As Point)
        If SelectedTower IsNot Nothing Then
            SelectedTower.Targeting = TargetingMode.Weakest
            UpdateTargetingButtonColors()
        End If
    End Sub

    Private Sub RemoveTower(tower As Tower)
        If tower Is Nothing Then Return
        Towers.Remove(tower)
        TowerLookup.Remove(tower.Id)
        RemoveElement(tower.Visual)
    End Sub

#End Region

#Region "Range Indicator"

    Private Sub ShowRangeIndicator(position As Vector2, range As Single)
        RangeIndicator.isVisible = True
        RangeIndicator.Size = New Vector2(range * 2.0F)
        RangeIndicator.Position = position - New Vector2(range)
        RangeIndicator.BringToFront()
    End Sub

    Private Sub HideRangeIndicator()
        RangeIndicator.isVisible = False
        RangeIndicator.Position = New Vector2(-1000, -1000)
    End Sub

    Private Function GetTowerRange(towerType As TowerType) As Single
        Select Case towerType
            Case TowerType.Spiral
                Return 200.0F
            Case TowerType.Burst
                Return 160.0F
            Case TowerType.Rapid
                Return 150.0F
            Case TowerType.Sniper
                Return 260.0F
            Case Else ' Point
                Return 180.0F
        End Select
    End Function

#End Region

#Region "Tooltip"

    Private Sub HandleMouseMove(currentPoint As Point, lastPoint As Point)
        LastMousePosition = currentPoint
    End Sub

    Private Sub UpdateTooltip()
        ' Hide tooltip when tower menu is visible
        If TowerMenuVisible Then
            HideTooltip()
            Return
        End If

        Dim mousePos As New Vector2(LastMousePosition.X, LastMousePosition.Y)
        Dim tooltipContent As String = Nothing

        ' Check tower buttons first
        If IsOverButton(SpiralTowerButton, mousePos) Then
            tooltipContent = GetTowerButtonTooltip(TowerType.Spiral)
        ElseIf IsOverButton(PointTowerButton, mousePos) Then
            tooltipContent = GetTowerButtonTooltip(TowerType.Point)
        ElseIf IsOverButton(BurstTowerButton, mousePos) Then
            tooltipContent = GetTowerButtonTooltip(TowerType.Burst)
        ElseIf IsOverButton(RapidTowerButton, mousePos) Then
            tooltipContent = GetTowerButtonTooltip(TowerType.Rapid)
        ElseIf IsOverButton(SniperTowerButton, mousePos) Then
            tooltipContent = GetTowerButtonTooltip(TowerType.Sniper)
        ElseIf IsOverButton(BombButton, mousePos) Then
            tooltipContent = "Bomb" & Environment.NewLine &
                            "Drag onto the path to place." & Environment.NewLine &
                            "Explodes after a timer, damaging" & Environment.NewLine &
                            "all enemies in the blast radius." & Environment.NewLine &
                            "Cost: $5"
        ElseIf IsOverButton(StartButton, mousePos) Then
            tooltipContent = "Click to start the game." & Environment.NewLine & "Enemies will spawn and follow the path."
        ElseIf IsOverButton(StopButton, mousePos) Then
            tooltipContent = "Click to stop the current game." & Environment.NewLine & "All progress will be reset."
        ElseIf IsOverButton(HostButton, mousePos) Then
            tooltipContent = "Host a multiplayer game." & Environment.NewLine & "Other players can join as clients."
        ElseIf IsOverButton(ClientButton, mousePos) Then
            tooltipContent = "Join a hosted game as a client." & Environment.NewLine & "Connect to localhost:4040."
        ElseIf GameRunning AndAlso IsInPlayField(mousePos) Then
            ' Check placed towers
            Dim tower As Tower = FindTowerAt(mousePos)
            If tower IsNot Nothing Then
                tooltipContent = GetPlacedTowerTooltip(tower)
            Else
                ' Check enemies
                Dim enemy As Enemy = FindEnemyAt(mousePos)
                If enemy IsNot Nothing Then
                    tooltipContent = GetEnemyTooltip(enemy)
                End If
            End If
        End If

        If tooltipContent IsNot Nothing Then
            ShowTooltip(tooltipContent, LastMousePosition)
        Else
            HideTooltip()
        End If
    End Sub

    Private Function IsOverButton(button As Button, mousePos As Vector2) As Boolean
        Dim rect As New Rectangle(CInt(button.Position.X), CInt(button.Position.Y), CInt(button.Size.X), CInt(button.Size.Y))
        Return rect.Contains(CInt(mousePos.X), CInt(mousePos.Y))
    End Function

    Private Function GetTowerButtonTooltip(towerType As TowerType) As String
        Dim name As String = ""
        Dim damage As Single = 0
        Dim range As Single = 0
        Dim fireRate As Single = 0
        Dim cost As Integer = 0
        Dim description As String = ""

        Select Case towerType
            Case TowerType.Spiral
                name = "Spiral Tower"
                damage = 6.0F
                range = 200.0F
                fireRate = 1.6F
                cost = 65
                description = "Fires projectiles in a spiral pattern."
            Case TowerType.Burst
                name = "Burst Tower"
                damage = 5.0F
                range = 160.0F
                fireRate = 0.9F
                cost = 75
                description = "Fires 3 projectiles in a spread."
            Case TowerType.Rapid
                name = "Rapid Tower"
                damage = 3.5F
                range = 150.0F
                fireRate = 2.4F
                cost = 40
                description = "Fast firing, low damage."
            Case TowerType.Sniper
                name = "Sniper Tower"
                damage = 14.0F
                range = 260.0F
                fireRate = 0.6F
                cost = 90
                description = "Long range, high damage, slow."
            Case Else ' Point
                name = "Point Tower"
                damage = 8.0F
                range = 180.0F
                fireRate = 1.2F
                cost = 50
                description = "Balanced tower. Good all-around."
        End Select

        Return $"{name}" & Environment.NewLine &
               $"{description}" & Environment.NewLine &
               $"Damage: {damage:F1}" & Environment.NewLine &
               $"Range: {range:F0}" & Environment.NewLine &
               $"Fire Rate: {fireRate:F1}/s" & Environment.NewLine &
               $"Cost: ${cost}"
    End Function

    Private Function GetPlacedTowerTooltip(tower As Tower) As String
        Dim typeName As String = tower.GetType().Name.Replace("Tower", " Tower")

        Return $"{typeName} (Lv.{tower.Level})" & Environment.NewLine &
               $"Targeting: {tower.Targeting.ToString()}" & Environment.NewLine &
               $"Damage: {tower.Damage:F1}" & Environment.NewLine &
               $"Range: {tower.Range:F0}" & Environment.NewLine &
               $"Fire Rate: {tower.FireRate:F1}/s" & Environment.NewLine &
               $"Sell Value: ${tower.GetSellValue()}" & Environment.NewLine &
               "Click to open tower menu"
    End Function

    Private Function GetEnemyTooltip(enemy As Enemy) As String
        Dim healthPercent As Single = (enemy.Health / enemy.MaxHealth) * 100.0F
        Dim typeName As String = "Normal"
        If enemy.TypeBlend > 0.7F Then
            typeName = "Tank"
        ElseIf enemy.TypeBlend > 0.4F Then
            typeName = "Tough"
        ElseIf enemy.TypeBlend < 0.2F Then
            typeName = "Fast"
        End If

        Return $"Enemy ({typeName})" & Environment.NewLine &
               $"Health: {enemy.Health:F0}/{enemy.MaxHealth:F0} ({healthPercent:F0}%)" & Environment.NewLine &
               $"Speed: {enemy.Speed:F0}"
    End Function

    Private Function FindEnemyAt(position As Vector2) As Enemy
        For Each enemy As Enemy In Enemies
            Dim distance As Single = Vector2.DistanceSquared(enemy.Position, position)
            If distance <= enemy.Radius * enemy.Radius * 2.0F Then ' Slightly larger hit area for easier hover
                Return enemy
            End If
        Next
        Return Nothing
    End Function

    Private Sub ShowTooltip(content As String, mousePos As Point)
        TooltipText.Text = content
        TooltipVisible = True

        ' Bring tooltip to front so it appears above other elements
        TooltipBackground.BringToFront()
        TooltipText.BringToFront()

        ' Calculate tooltip size based on text
        Dim padding As Single = 8.0F
        Dim textSize As Vector2 = TooltipText.Size
        If textSize.X < 10 Then textSize = New Vector2(200, 80) ' Default size if text not measured yet

        ' Position tooltip near mouse, but keep on screen
        Dim tooltipX As Single = mousePos.X + 15.0F
        Dim tooltipY As Single = mousePos.Y + 15.0F

        ' Clamp to screen bounds
        If tooltipX + textSize.X + padding * 2 > sender.Window.ClientBounds.Width Then
            tooltipX = mousePos.X - textSize.X - padding * 2 - 10.0F
        End If
        If tooltipY + textSize.Y + padding * 2 > sender.Window.ClientBounds.Height Then
            tooltipY = mousePos.Y - textSize.Y - padding * 2 - 10.0F
        End If

        TooltipBackground.Position = New Vector2(tooltipX, tooltipY)
        TooltipBackground.Size = New Vector2(textSize.X + padding * 2, textSize.Y + padding * 2)
        TooltipText.Position = New Vector2(tooltipX + padding, tooltipY + padding)

        TooltipBackground.BackgroundColor = New Color(30, 30, 30, 230)
    End Sub

    Private Sub HideTooltip()
        If TooltipVisible Then
            TooltipVisible = False
            TooltipText.Text = ""
            TooltipBackground.Position = New Vector2(-1000, -1000) ' Move off-screen
        End If
    End Sub

#End Region

#Region "IDisposable Support"

    Protected Overrides Sub Dispose(disposing As Boolean)
        If disposing Then
            ' Stop the game first
            If GameRunning Then
                StopGame()
            End If

            ' Dispose networking resources - this stops the background threads
            Try
                If Server IsNot Nothing Then
                    Server.Dispose()
                    Server = Nothing
                End If
            Catch
            End Try

            Try
                If Client IsNot Nothing Then
                    Client.Dispose()
                    Client = Nothing
                End If
            Catch
            End Try

            ' Clear pending queues
            Dim dummy As MapDataMessage = Nothing
            While PendingMap.TryDequeue(dummy)
            End While

            Dim dummy2 As GameStateMessage = Nothing
            While PendingStates.TryDequeue(dummy2)
            End While
        End If

        MyBase.Dispose(disposing)
    End Sub

#End Region

End Class
