<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>Designer</RootNamespace>
    <AssemblyName>Project Z UI Designer</AssemblyName>
    <OptionStrict>On</OptionStrict>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <UseWPF>true</UseWPF>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SocketJack" Version="1.3.0" />
    <PackageReference Include="LibTessDotNet" Version="1.1.15" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
    <None Include="app.config" />
    <None Include="packages.config" />

    <Content Include="Content\Fonts\Segoe UI\SegoeUI_10.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_12.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_14.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_18.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_24.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_36.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_48.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Fonts\Segoe UI\SegoeUI_72.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scenes\MainScene.xaml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project Z Windows.vbproj" />
  </ItemGroup>

</Project>
