<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework Condition="'$(ProjectZTestTargetFramework)' == ''">net8.0-windows7.0</TargetFramework><TargetFramework Condition="'$(ProjectZTestTargetFramework)' != ''">$(ProjectZTestTargetFramework)</TargetFramework><OutputType>Exe</OutputType><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../cs/BuildTime.csproj"/><ProjectReference Include="../vb/BuildTime.vbproj"/><ProjectReference Include="../DesignerOnly/cs/DesignerOnly.csproj"/><ProjectReference Include="../DesignerOnly/vb/DesignerOnly.vbproj"/><Content Include="../../../../Project Z Application/Content/Fonts/Segoe UI/*.xnb" Link="Content/Fonts/Segoe UI/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest"/></ItemGroup></Project>