<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net8.0-windows7.0</TargetFramework><AssemblyName>DesignerOnlyVB</AssemblyName><RootNamespace></RootNamespace><ProjectZXamlMode>DesignerOnly</ProjectZXamlMode></PropertyGroup>
 <ItemGroup><ProjectZXaml Include="View.xaml" /></ItemGroup>
 <Import Project="../../../../../Project Z XAML Codegen/ProjectZ.Xaml.targets" />
</Project>
